---
title: what does a personalized clinical trial look like?(Draft)
author: 'Apoorva Srinivasan'
date: '2020-08-18'
slug: biostatistics
categories:
  - Statistics
tags:
  - Statistics
description: ''
---

For many decades, randomized controlled trials have been the gold standard for clinical trials. You take a group of people with some condition, and you randomly assign each of those people to one of two (or more) treatment groups. These groups are then compared on a predefined measured response.  Ideally, noone – not the researcher, not the patients – knows who is in which group until the end of the study.


# looking past one-size fits all approach

The study I’ve just described is called a parallel-group trial, and the vast majority of randomized controlled trials (RCTs) follow this design. Modern clinical evidence depends on such mixture of parallel-group (majority) and crossover (minority) trials, with a few other designs (factorial, cluster, split-body, etc.) thrown in. Regardless of design specifics, however, all of this evidence suffers from the same key limitation: treatment effects are estimated at the population level, leading to one-size-fits-all recommendations that are not necessarily appropriate for individual patients. The extent to which results from clinical trials are relevant to “real-life” patient populations is an [open question](link) Clinicians following evidence-based treatment guidelines are often left to their own judgement to tackle heterogeneity in both treatment efficacy and side effects.



# renewed momentum in the precision medicine era

At its core, precision medicine seeks solutions to such challenges. Personalized trial designs, also known as N-of-1 trials, have been developed to address this fundamental problem but are not yet part of the arsenal of precision medicine. Currently, these designs are rarely used in clinical practice, in evidence-genesis, or in the formation of guidelines.For the last decade, there has been increasing interest in two streams of development in precision medicine. First is the integration of electronic medical records capturing longitudinal data and providing clinical phenotypes into decision making tools for precision medicine. Secondly, the advance in genomic medicine and pharmacogenomics research provides an expanding arsenal of genetic predictors of disease and health outcomes. Together these two streams provide a unique framework for an individualized diagnostic and therapeutic approach. 


# enter n-of-1 clinical trials


N-of-1 or single subject clinical trials consider an individual patient as the sole unit of observation in a study investigating the efficacy or side-effect profiles of different interventions. The ultimate goal of an n-of-1 trial is to determine the optimal or best intervention for an individual patient using objective data-driven criteria. Such trials can leverage study design and statistical techniques associated with standard population-based clinical trials, including randomization, washout and crossover periods, as well as placebo controls. 






