---
title: data science interview questions and resources
author: ''
date: '2020-08-17'
slug: data-science-interview-questions-and-resources
categories:
  - Development
tags:
  - Development
description: ''
---

As a recent graduate, I spent a better part of this year applying and interviewing for data science jobs. By going through a process of hundreds of applications, a dozen phone screens and four final rounds of interviews, I have accumulated a significant amount of resources and questions that have helped me prepare and land my dream data scientist role. Organized by categorizies, you will find over 50 interview questions along with some resources to help you brush up your skills and crush that interview!

Please note that the questions below are more suitable for entry level data scientist position since that is what I have experience with.


# machine learning

Machine Learning questions generally tend to be open ended in an interview where you will most likely be asked to defend your approaches in your previous projects or take-home tests. Be prepared to measure the "goodness" of a feature for a company's product and make sure to approach it in a scientific principled way. 

1. Analyze this dataset and give me a model that can predict this response variable.

2. What could be some issues if the distribution of the test data is significantly different than the distribution of the training data?

3. What are some ways I can make my model more robust to outliers?

4. Explain how decision trees work.

5. How can you make sure that you don’t analyze something that ends up meaningless?

6. What are some differences you would expect in a model that minimizes squared error, versus a model that minimizes absolute error? In which cases would each error metric be appropriate?

7. What error metric would you use to evaluate how good a binary classifier is? What if the classes are imbalanced? What if there are more than 2 groups?

8. What is regularization and where might it be helpful? What is an example of using regularization in a model?

9. Why might it be preferable to include fewer predictors over many?

10. What is regularization and why is it useful?

11. Drawbacks of a linear model?

12. What is kernal trick?

13. How can you say time-series is stationary?

### resources for machine learning:

* [Chris Albon's Machine Learning Flashcards](https://machinelearningflashcards.com)
* [Over 100 DS Questions](https://towardsdatascience.com/over-100-data-scientist-interview-questions-and-answers-c5a66186769a)
* [How to Prepare for a Machine Learning Interview](https://blog.udacity.com/2016/05/prepare-machine-learning-interview.html)

# statistical inference

Data scientist interview is incomplete without testing your knowledge in statistical concepts. The best way to prepare for this would be going through your course material from school or a related textbook. Below are some questions to checking your understanding and indentify gaps to fill in later


14. What is maximum likelihood estimation? Could there be any case where it doesn’t exist?

15. What’s the difference between a MAP, MOM, MLE estimator? In which cases would you want to use each?

16. What is the difference between covariance and correlation?

17. What is power analysis?

18. What is a confidence interval and how do you interpret it?

19. What is the basic idea behind bootstrapping?

20. What is unbiasedness as a property of an estimator? Is this always a desirable property when performing inference? What about in data analysis or predictive modeling?

21. What is z-scoring? Why would you do it?

22. What is the law of large numbers?

23. What are eigenvalues and eigenvectors?

24. What is the difference between sentivity and specificity?

25. What is a random variable?

26. What are the drawbacks of locally weighted average?

27. What are the different correlation measures between continuous and categorical variables

### resources for statistical inference:

* [Elements of statistical learning](https://web.stanford.edu/~hastie/ElemStatLearn/)

* [Practical Statistics for Data Scientists](https://www.amazon.com/Practical-Statistics-Data-Scientists-Essential/dp/149207294X/ref=sr_1_2?crid=2VWCQJAQNJ611&dchild=1&keywords=practical+statistics+for+data+scientists&qid=1597668184&s=books&sprefix=practica%3B+statistics+%2Cstripbooks%2C156&sr=1-2)

# programming

Programming tests for data scientists usually involve querying with SQL. This can be done over the phone or onsite.  Based on the team, role and the organization, your interviews will widely vary between being heavy on statistics or software development. To practice programming related questions, I highly recommend cracking the coding interview.

28. Write an algorithm that can calculate the square root of a number.

29. Given a list of numbers, can you return the outliers?

30. When can parallelism make your algorithms run faster? When could it make your algorithms run slower?

31. What are the different types of joins? What are the differences between them?

32. Why might a join on a subquery be slow? How might you speed it up?

### resources for programming:

* [Interview Query](https://www.interviewquery.com)
* [W3Schools for SQL](https://www.w3schools.com)
* [Cracking the Coding Interview](http://www.crackingthecodinginterview.com)


# probability

33. How can you generate a random number between 1 - 7 with only a die?

34. How can you get a fair coin toss if someone hands you a coin that is weighted to come up heads more often than tails?

35. You have an 50-50 mixture of two normal distributions with the same standard deviation. How far apart do the means need to be in order for this distribution to be bimodal?

36. Given draws from a normal distribution with known parameters, how can you simulate draws from a uniform distribution?

37. A certain couple tells you that they have two children, at least one of which is a girl. What is the probability that they have two girls?

38. How many ways can you split 12 people into 3 teams of 4?

39. On a dating site, users can select 5 out of 24 adjectives to describe themselves. A match is declared between two users if they match on at least 4 adjectives. If Alice and Bob randomly pick adjectives, what is the probability that they form a match?

40. Let’s say you have a very tall father. On average, what would you expect the height of his son to be? Taller, equal, or shorter? What if you had a very short father?

41. What’s the expected number of coin flips until you get two heads in a row? What’s the expected number of coin flips until you get two tails in a row?

42. Let’s say we play a game where I keep flipping a coin until I get heads. If the first time I get heads is on the nth coin, then I pay you 2n-1 dollars. How much would you pay me to play this game?

43. You have a 0.1% chance of picking up a coin with both heads, and a 99.9% chance that you pick up a fair coin. You flip your coin and it comes up heads 10 times. What’s the chance that you picked up the fair coin, given the information that you observed?

44. You have two coins, one of which is fair and comes up heads with a probability 1/2, and the other which is biased and comes up heads with probability 3/4. You randomly pick coin and flip it twice, and get heads both times. What is the probability that you picked the fair coin?

### resources for probability:

* [Brilliant](https://brilliant.org)
* [120 Questions for Data Science Interviews](https://www.datasciencequestions.com)


# communication

45. Explain to me a technical concept related to the role that you’re interviewing for.

46. Introduce me to something you’re passionate about.

47. How will you report statistical analysis to a non-technical staff?

48. Tell me about a data project that you’ve done with a team. What did you add to the group?

49. Tell me about a dataset that you’ve analyzed. What techniques did you find helpful and which ones didn’t work?

50. What’s your favorite algorithm? Can you explain it to me?

51. How could you help the generate public understanding towards the importance of using data to generate insights?


# parting thoughts

Please consider the above questions as a workbook to review some topics and identify gaps in areas you can fill in later. Interviews are hard, but there is a silver lining in that they serve as a forcing function for learning. 

Thanks to others sharing what they learned, I was able to fail, learn from it, and then do it over again until I landed a job that I loved. I'm confident that with these resources and the right mindset, you'll do great too. Good luck! 





